---
apiVersion: v1
kind: Service
metadata:
  name: my-sqlservice
  labels:
    app: springmysql
spec:
#  type: NodePort
  ports:
  - port: 3306
  selector:
    app: springmysql
#service 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springmysql
  template:
    metadata:
      labels:
        app: springmysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value:  root
        - name: MYSQL_ROOT_PASSWORD
          value:  dummypassword
        - name: MYSQL_USER
          value:  todos-user
        - name: MYSQL_PASSWORD
          value:  dummytodos
        - name: MYSQL_DATABASE
          value:  todos
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
