apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment #name of replicaset
  labes:
    app: my-replicaset
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: harshad #name of pods
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
