
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: nginx-pod #name of replicaset
  labes:
    app: my-replicaset
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
