apiVersion: apps/v1
kind: Pod
metadata:
  name: hari
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "5Mi"  # require minimum memory to run a pod
        limits:
          memory: "10Mi" #always greater thatn requests 
