apiVersion: apps/v1
kind: Service
metadata:
  name: sample-web

spec:
  type: NodePort #Loadbalancer
  ports:
    - targetport: 8080
      port: 8080
      nodeport: 30080 #optional or (use can assign 30000 to 32567)
  selector:
    name: webapplication #name of pod
 ---
apiVersion: apps/v1
kind: Pod
metadata:
  name: webapplication
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
  
