apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx #we have to mention only labels of pods matched labels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx #this is name is taken from below labelsfor replicaset
  template:
    metadata:
      labels:
        app: nginx  #this is the name we have mention in service as a selector
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80





#we can use any of these both yaml files











apiVersion: v1
kind: Service
metadata:
  name: sample-web

spec:
  type: NodePort #Loadbalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30080 #optional or (use can assign 30000 to 32567)
  selector:
#    name: webapplication #name of pod
    app: mouse
 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mouse
  template:
    metadata:
      name: vijay
      labels:
        app: mouse
  spec:
    containers:
      - name: nginx
        image: nginx
  
